name: Build LaTeX document
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build-latex-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Save result
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
